trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      AMD64 (x64):
        dockerFile: 'amd64.stretch'
        dockerImage: 'Debian Stretch (AMD64)'
        dockerTags: 'amd64'
      i386 (x86):
        dockerFile: 'i386.stretch'
        dockerImage: 'Debian Stretch (i386)'
        dockerTags: 'i386'
      ARMv6hf-stretch (Raspberry Pi v1 & ZERO):
        dockerFile: 'armv6hf.stretch'
        dockerImage: 'Debian Stretch (Raspberry Pi v1 & ZERO)'
        dockerTags: 'armv6hf'
      ARMv7hf-stretch (Raspberry Pi 2 & 3):
        dockerFile: 'armv7hf.stretch'
        dockerImage: 'Debian Stretch (Raspberry Pi 2 & 3)'
        dockerTags: 'armv7hf'
      ARMv6hf-buster (Raspberry Pi v1 & ZERO):
        dockerFile: 'armv6hf.buster'
        dockerImage: 'Debian Buster (Raspberry Pi v1 & ZERO)'
        dockerTags: 'armv6hf-buster'
      ARMv7hf-buster (Raspberry Pi 2 & 3):
        dockerFile: 'armv7hf.buster'
        dockerImage: 'Debian Buster (Raspberry Pi 2 & 3)'
        dockerTags: 'armv7hf-buster'
      ARMv8 (Generic AARCH64):
        dockerFile: 'aarch64.stretch'
        dockerImage: 'ARMv8 (Generic AARCH64)'
        dockerTags: 'aarch64'
  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: 'Docker Hub'
  - task: Docker@2
    displayName: 'Build $(dockerImage) and Push to Docker Hub'
    inputs:
      command: buildAndPush
      repository: 'hyperionproject/hyperion-ci'
      containerRegistry: 'Docker Hub'
      Dockerfile: $(dockerFile)
      tags: $(dockerTags)
  - task: Docker@2
    displayName: Logout of Docker Hub
    inputs:
      command: logout
      containerRegistry: 'Docker Hub'

- job: RPi
  pool:
    name: 'RPi3'
  strategy:
    matrix:
      Raspbian Stretch:
        dockerFile: 'raspbian.stretch'
        dockerImage: 'Raspbian Stretch'
        dockerTags: 'rpi-raspbian-stretch'
      Raspbian Buster:
        dockerFile: 'raspbian.buster'
        dockerImage: 'Raspbian Buster'
        dockerTags: 'rpi-raspbian-buster'
  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: 'Docker Hub'
  - task: Docker@2
    displayName: 'Build $(dockerImage) and Push to Docker Hub'
    inputs:
      command: buildAndPush
      repository: 'hyperionproject/hyperion-ci'
      containerRegistry: 'Docker Hub'
      Dockerfile: $(dockerFile)
      tags: $(dockerTags)
  - task: Docker@2
    displayName: Logout of Docker Hub
    inputs:
      command: logout
      containerRegistry: 'Docker Hub'
