name: Docker CI (APT)

on:
  push:
    branches:
      - master

jobs:
  setup:
    name: Setup Matrix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set APT matrix
        id: apt-ppa
        run: |
          APT=$(jq -n '.include |= [ inputs[] | select(.["exclude"] != true)]' apt/*.json --compact-output)
          echo "apt=${APT}" >> $GITHUB_OUTPUT

    outputs:
      apt-matrix: ${{ steps.apt-ppa.outputs.apt }}

  build:
    name: ${{ matrix.description }}
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.apt-matrix) }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and tag docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}:${{ matrix.tag }} --build-arg DIST=${{ matrix.dist }} --build-arg SUITE=${{ matrix.tag }} --build-arg REPOSITORY="${{ github.server_url}}/${{ github.repository_owner }}" -f apt/${{ matrix.file }} .

      - name: Publish to GitHub Container/Package Registry
        env:
            SECRET_DOCKER_CI: ${{ secrets.DOCKER_CI }}
        if: ${{ env.SECRET_DOCKER_CI != null }}
        run: |
          echo ${{ secrets.DOCKER_CI }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          docker push ghcr.io/${{ github.repository_owner }}/${{ matrix.file }}:${{ matrix.tag }}
