name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  Docker:
    name: ${{ matrix.dockerOS }} ${{ matrix.dockerTag }} ${{ matrix.description }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dockerImage: [ x86_64, armv6l, armv7l, aarch64 ]
        dockerTag: [ buster, bullseye, bookworm ]
        include:
          - dockerImage: x86_64
            dockerOS: Debian
            description: (x86_64)
            os: ubuntu-latest
          - dockerImage: armv6l
            dockerOS: Debian
            description: (Raspberry Pi v1 & ZERO)
            os: ubuntu-latest
          - dockerImage: armv7l
            dockerOS: Debian
            description: (Raspberry Pi 2 & 3)
            os: ubuntu-latest
          - dockerImage: aarch64
            dockerOS: Debian
            description: (Generic AARCH64)
            os: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and tag docker image
        run: |
          docker build -t ghcr.io/hyperion-project/${{ matrix.dockerImage }}:${{ matrix.dockerTag }} --build-arg SUITE=${{ matrix.dockerTag }} -f ${{ matrix.dockerImage }} .

      - name: Publish to GitHub Container/Package Registry
        env:
            SECRET_DOCKER_CI: ${{ secrets.DOCKER_CI }}
        if: ${{ env.SECRET_DOCKER_CI != null }}
        run: |
          echo ${{ secrets.DOCKER_CI }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/hyperion-project/${{ matrix.dockerImage }}:${{ matrix.dockerTag }}
