name: Docker CI

on:
  push:
    branches:
      - master

jobs:
  Docker:
    name: ${{ matrix.dockerOS }} ${{ matrix.dockerTag }} ${{ matrix.description }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dockerImage: [ x86_64, armv6l, armv7l, aarch64, rpi-raspbian ]
        dockerTag: [ stretch, buster ]
        include:
          - dockerImage: x86_64
            dockerOS: Debian
            description: (x86_64)
            os: ubuntu-latest
          - dockerImage: armv6l
            dockerOS: Debian
            description: (Raspberry Pi v1 & ZERO)
            os: ubuntu-latest
          - dockerImage: armv7l
            dockerOS: Debian
            description: (Raspberry Pi 2 & 3)
            os: ubuntu-latest
          - dockerImage: aarch64
            dockerOS: Debian
            description: (Generic AARCH64)
            os: ubuntu-latest
          - dockerImage: rpi-raspbian
            dockerOS: Raspbian
            description:  ""
            os: RPi3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and tag docker image
        run: |
          docker build -t ghcr.io/hyperion-project/${{ matrix.dockerImage }}:${{ matrix.dockerTag }} -f ${{ matrix.dockerImage }}.${{ matrix.dockerTag }} .

      - name: Publish to GitHub Container/Package Registry
        run: |
          echo ${{ secrets.DOCKER_CI }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/hyperion-project/${{ matrix.dockerImage }}:${{ matrix.dockerTag }}
