name: Docker CI
on:
  push:
    branches:
      - master

jobs:
  Linux:
    name: ${{ matrix.dockerStage }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        dockerImage: [ x86_64, armv6l, armv7l, aarch64, rpi-raspbian ]
        include:
          - dockerImage: x86_64
            dockerTag: stretch
            dockerStage: Debian Stretch (x86_64)
            dockerFile: x86_64.stretch
            os: ubuntu-latest

          - dockerImage: x86_64
            dockerTag: buster
            dockerStage: Debian Buster (x86_64)
            dockerFile: x86_64.buster
            os: ubuntu-latest

          - dockerImage: armv6l
            dockerTag: stretch
            dockerStage: Debian Stretch (Raspberry Pi v1 & ZERO)
            dockerFile: armv6l.stretch
            os: ubuntu-latest

          - dockerImage: armv6l
            dockerTag: buster
            dockerStage: Debian Buster (Raspberry Pi v1 & ZERO)
            dockerFile: armv6l.buster
            os: ubuntu-latest

          - dockerImage: armv7l
            dockerTag: stretch
            dockerStage: Debian Stretch (Raspberry Pi 2 & 3)
            dockerFile: armv7l.stretch
            os: ubuntu-latest

          - dockerImage: armv7l
            dockerTag: buster
            dockerStage: Debian Buster (Raspberry Pi 2 & 3)
            dockerFile: armv7l.buster
            os: ubuntu-latest

          - dockerImage: aarch64
            dockerTag: stretch
            dockerStage: Debian Stretch (Generic AARCH64)
            dockerFile: aarch64.stretch
            os: ubuntu-latest

          - dockerImage: aarch64
            dockerTag: buster
            dockerStage: Debian Stretch (Generic AARCH64)
            dockerFile: aarch64.buster
            os: ubuntu-latest

          - dockerImage: rpi-raspbian
            dockerTag: stretch
            dockerStage: Raspbian Stretch
            dockerFile: raspbian.stretch
            os: RPi3

          - dockerImage: rpi-raspbian
            dockerTag: buster
            dockerStage: Raspbian Buster
            dockerFile: raspbian.buster
            os: RPi3

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build and tag docker image
        run: |
          docker build -t ghcr.io/hyperion-project/{{ matrix.dockerImage }}:${{ matrix.dockerTag }} -f ${{ matrix.dockerFile }} .

      - name: Publish to GitHub Container Registry
        run: |
          echo ${{ secrets.DOCKER_CI }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/hyperion-project/{{ matrix.dockerImage }}:${{ matrix.dockerTag }}
