name: Package Repository
run-name: |
  ${{ github.event_name == 'schedule' && '⏰ Scheduled build' || '' }}
  ${{ github.event_name == 'push' && format('🌱 Push build - {0}', github.event.head_commit.message) || '' }}

on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches: [ master ]

jobs:

  ubuntu_debian_fedora:
    name: 🐧 ${{ matrix.os.description }} Qt ${{ matrix.qt_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [
          { distribution: ubuntu, codename: jammy,    description: Ubuntu 22.04 (Jammy Jellyfish), target_platform: "['amd64', 'arm64', 'armv7']" },
          { distribution: ubuntu, codename: noble,    description: Ubuntu 24.04 (Noble Numbat),    target_platform: "['amd64', 'arm64', 'armv7']" },
          { distribution: ubuntu, codename: oracular, description: Ubuntu 24.10 (Oracular Oriole), target_platform: "['amd64', 'arm64', 'armv7']" },
          { distribution: ubuntu, codename: plucky,   description: Ubuntu 25.04 (Plucky Puffin),   target_platform: "['amd64', 'arm64', 'armv7']" },
          { distribution: debian, codename: bullseye, description: Debian 11.x  (Bullseye),        target_platform: "['amd64', 'arm64', 'armv6', 'armv7']" },
          { distribution: debian, codename: bookworm, description: Debian 12.x  (Bookworm),        target_platform: "['amd64', 'arm64', 'armv6', 'armv7']" },
          { distribution: debian, codename: trixie,   description: Debian 13.x  (Trixie),          target_platform: "['amd64', 'arm64', 'armv6', 'armv7']" },
          { distribution: fedora, codename: 39,       description: Fedora 39,                      target_platform: "['amd64', 'arm64']" },
          { distribution: fedora, codename: 40,       description: Fedora 40,                      target_platform: "['amd64', 'arm64']" },
          { distribution: fedora, codename: 41,       description: Fedora 41,                      target_platform: "['amd64', 'arm64']" },
          { distribution: fedora, codename: 42,       description: Fedora 42,                      target_platform: "['amd64', 'arm64']" }
        ]
        qt_version: [ 5, 6 ]
        # Qt6 on Debian Bullseye (only armv6) is excluded in reusable workflow qt5_6.yml because target_platform is passed as string to reusable workflow

    uses: ./.github/workflows/qt5_6.yml
    secrets: inherit
    with:
      distribution: ${{ matrix.os.distribution }}
      codename: ${{ matrix.os.codename }}
      qt_version: ${{ matrix.qt_version }}
      target_platform: ${{ matrix.os.target_platform }}